### ISSUE TITLE
Fix mapping file for the person object

### ISSUE THREAD

**Issue by jaredramirez** [byte-pushers/myfamily#9]
The file is not recognizing the http://www.jboss.org/xsd/jaxb/intros schema, causing the mapping to be invalid

**Comment by pouncilt** [comment]
download it from domo project under schema folder.  And then figure out how to make IntelliJ see this file by using XML catalogs.  Call me if you have questions.

Tonté

**Comment by jaredramirez** [comment]
Thanks, I thought it was included in the jboss-jaxb-intros jar. It’s recognizing it now. 

jared
